export type ServiceTone = "rose" | "paper" | "gray" | "blush";

export const serviceCards: {
  title: string;
  body: string;
  span: 7 | 5;
  rotate: string;
  tone: ServiceTone;
}[] = [
  {
    title: "Web apps and MVPs",
    body: "Next.js and TypeScript, front to back. Dashboards, internal tools, small SaaS products, and new features for an app you already have.",
    span: 7,
    rotate: "-0.7deg",
    tone: "rose",
  },
  {
    title: "Mobile apps, all the way to the stores",
    body: "React Native with Expo. I handle the builds, store listings, Apple and Google review, and in-app purchases. That last stretch is where most mobile projects stall.",
    span: 5,
    rotate: "0.6deg",
    tone: "paper",
  },
  {
    title: "Work inside your existing codebase",
    body: "Inherited, abandoned, legacy, or generated by an AI tool. I read what's there first, fix the root cause, and leave it easier to maintain. Bug fixes and code audits are welcome too.",
    span: 5,
    rotate: "0.5deg",
    tone: "gray",
  },
  {
    title: "WordPress and Shopify",
    body: "Custom classic WordPress themes, redesigns inside your current branding, and ongoing maintenance. Shopify store builds and app embeds.",
    span: 7,
    rotate: "-0.5deg",
    tone: "blush",
  },
];

export const servicesFootnote =
  "Figma to code, design systems, accessibility, deploy pipelines, and moving your product off a platform you don't own.";
